---
language: go
go:
  - tip

sudo: required

services:
  - docker

## Need docker-compose 1.5.x for Variable Interpolation
env:
  DOCKER_COMPOSE_VERSION: 1.5.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - make clean lint build
  - make test
  - make integration
