# This demonstration of containerbuddy has port mappings so we can use it
# on docker-machine locally.

etcd:
    image: quay.io/coreos/etcd:v2.0.8
    command: >
      -name etcd0
      -advertise-client-urls http://etcd:2379,http://etcd:4001
      -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001
      -initial-advertise-peer-urls http://etcd:2380
      -listen-peer-urls http://0.0.0.0:2380
      -initial-cluster-token etcd-cluster-1
      -initial-cluster etcd0=http://etcd:2380
      -initial-cluster-state new
    mem_limit: 256m
    hostname: etcd
    expose:
    - 2379
    - 2380
    - 4001
    ports:
    - 4001:4001
    restart: always

nginx:
    image: 0x74696d/containerbuddy-etcd-demo-nginx
    mem_limit: 512m
    expose:
    - 80
    links:
    - etcd:etcd
    ports:
    - 8080:80
    restart: always
    command: >
      /opt/containerbuddy/containerbuddy
      -config file:///opt/containerbuddy/nginx.json
      nginx -g "daemon off;"

app:
    image: 0x74696d/containerbuddy-etcd-demo-app
    mem_limit: 512m
    expose:
    - 8000
    links:
    - etcd:etcd
    ports:
    - 8000
    restart: always
    command: >
      /opt/containerbuddy/containerbuddy
      -config file:///opt/containerbuddy/app.json
      /usr/local/bin/node /usr/local/bin/http-server /srv -p 8000
